swagger: '2.0'
info:
  version: 0.0.1
  title: Flywheel
host: 'dev.flywheel.io'
basePath: '/api'
schemes:
- 'https'
produces:
- 'application/json'
consumes:
- 'application/json'

tags:
  - name: users
    description: User operations
  - name: groups
    description: Group operations
  - name: projects
    description: Project operations
  - name: sessions
    description: Session operations
  - name: acquisitions
    description: Acquisition operations
  - name: analyses
    description: Analysis operations
  - name: collections
    description: Collection operations
  - name: files
    description: File upload/download operations
  - name: dataexplorer
    description: Search operations
  - name: devices
    description: Device operations
  - name: modalities
    description: Modality operations
  - name: gears
    description: Gear operations
  - name: rules
    description: Gear rule configuration
  - name: jobs
    description: Job operations
  - name: reports
    description: Site-wide reports
  - name: batch
    description: Batch job operations
  - name: views
    description: Data view operations
  - name: containers
    description: Abstract container operations
  - name: site
    description: Site level operations
  - name: default

paths:
  $include:
    - paths/login.yaml
    - paths/download.yaml
    - paths/upload-by-label.yaml
    - paths/upload-by-reaper.yaml
    - paths/upload-by-uid.yaml
    - paths/upload-match-uid.yaml
    - paths/clean-packfiles.yaml
    - paths/engine.yaml
    - paths/config.yaml
    - paths/config-js.yaml
    - paths/site.yaml
    - paths/version.yaml
    - paths/users.yaml
    - paths/jobs.yaml
    - paths/gears.yaml
    - paths/devices.yaml
    - paths/modalities.yaml
    - paths/groups.yaml
    - paths/collections.yaml
    - paths/subjects.yaml
    - paths/sessions.yaml
    - paths/acquisitions.yaml
    - paths/projects.yaml
    - paths/report.yaml
    - paths/batch.yaml
    - paths/analyses.yaml
    - paths/site-rules.yaml
    - paths/dataexplorer.yaml
    - paths/resolver.yaml
    - paths/data-views.yaml
    - paths/containers.yaml
    - paths/tree.yaml
    - paths/providers.yaml

securityDefinitions:
  ApiKey:
    type: apiKey
    in: header
    name: Authorization
    description: |
      Your API key is available on your Profile page from within the Flywheel Application.
      **NOTE:** The API key should be prefixed with `scitran-user` if you're testing APIs on this page.

      e.g. `scitran-user dev.flywheel.io:DFCAds356sdvd`.

security:
  - ApiKey: []

responses:
  $ref: responses/index.yaml

